Feature/automatic stones
milescrawford/joseki pull request #7
Opened 2024-04-25 02:58 UTC by RobertChrist

Each of the below items are a separate commit in the PR.

BugFixes:

- Resolves a display issue when the joseki ends with passing
- Corrects missing await statements in async/await implementation

New Feature:
- Implements the ability to add non-joseki stones to a joseki.  These stones are called 'Automatic' stones.
    - Automatic stones are played by the AI without user input.  Allowing users to define stones that should be placed on the board before or after the joseki is played/tested.
    - While the AI is placing these stones, user input is ignored.
    - Help page has been updated.
    - Two helpful example josekis have been added in a (by default disabled) starter joseki group

Feature Implementation Detail:
- Some method names have been given a standardized naming pattern:
    -  Action methods are play(), pass(), editAdd(), etc.
    - Move methods are Action methods that first check if the move is in the joseki tree.  For example: playMove(), passMove(), playAutomaticMove(), etc.
    - Move methods that handle user events, are called handle methods.  For example: handlePlayMove(), handlePassMove()

2024-04-25 17:45 UTC, milescrawford requested changes
A few questions from testing:

- [ ] Would it still serve your purpose to just allow "setup" moves instead of automatic moves at any point in the joseki, switching back and forth, etc? It may be simpler UI/mentally to allow groups to have "setup" stones, so that all joseki in a group begin from a given position. But maybe I'm missing your use case.

- [ ] Is it intentional that the first move is numbered "2" when using automatic stones? Seems like the moves to be played should still start with 1.
![Screen Shot 2024-04-25 at 10 32 24 AM](https://github.com/milescrawford/joseki/assets/11055723/b8077b03-62ba-4ee9-967d-94b4b6470d74)
Oooh, actually I see now that move "1" was a pass. I think maybe the automatic moves should still be numbered, then the whole will still make sense.


- [ ] It seems that automatic stones don't interact very smoothly with passing. Maybe passes aren't executed automatically? My idea to use this feature is "make a group of joseki about approaching an enclosure", but the AI only ever plays the first automatic move - I have to do the passing to let the AI finish the enclosure.

2024-04-26 01:41 UTC, RobertChrist commented
Heyo!

So I like the idea of calling these Setup Stones.  That's exactly what I was initially thinking.  

If we want to do setup-only stones (which makes sense), then I think I would make the following changes:

1. Rename Automatic Stones to Setup Stones
2. Make Setup Stones all place at once before the joseki (no need to watch them be placed sequentially)
3. Update pre-joseki passes to be automatic, and just speed through them without a message.
4. Disable placing setup stones once the first joseki stone is placed on the edit page, so they can only be pre-joseki.

Possible Improvements could be:
1. Update the Edit UI so a person can place all the black/white setup stones they want without having to pass.
2. Hash the setup position, so the order the setup stones are placed in doesn't matter when constructing the tree.

.

As I was playing with this, I found I liked being able to continue josekis with automatic stone placement, though.

Sitting here, I'm realizing I don't have the most compelling reason for it.  But maybe I could show you what I mean?

There's a joseki in this file called "3-3 Invasion - AI - White Owns Supporting corner - Black Tries to Extend from Wall"
[exampleJosekiForMiles.json](https://github.com/milescrawford/joseki/files/15123680/exampleJosekiForMiles.json)

In this joseki, the user will experience:

1. The board sets up the setup stones.
2. The user finishes the 3-3 invasion joseki
3. The board goes "okay, you completed the joseki.  Now what would you do if black tried to extend the wall here?"
4. You play a few more joseki-like moves to practice a response to a common continuation off of the joseki you just finished.

I could split this joseki up into 2 different josekis using only setup stones.  But it seems so much cooler / more interactive to do it this way?

But I agree it could use somework.  Handling passes like this is a bit weird.  Because there's no way to tell which passes are automatic vs manual, I just left them all as manual, which is clearly a bit confusing.  

I don't know.  I'm okay with paring this back down to just the Setup Stone idea above too.  What do ya think?

2024-04-26 17:54 UTC, milescrawford commented
I'd love for you to have automatic moves everywhere, but I think the auto/manual problem is serious - what if the user has one joseki with a manual move at a3, and another with an automatic move at a3? And same for passing. In the practice session, we can't tell what to do. 

Switching to setup stones does avoid this confusion.

Can you think of a way to handle the conflicting auto/manual issue? If so, go for it. If not, let's switch to setup.

2024-11-26 00:23 UTC, milescrawford commented
I'm closing this as abandoned for now.

2024-11-26 02:58 UTC, RobertChrist commented
@milescrawford - Hey!  The family caught Covid in May, and then we moved, which more or less flipped my life upside down.

I've got an updated version of the code with your recommended changes sitting in another window, it'll just likely be a bit while longer before I get an actually free weekend to test it, haha.  Sorry about the delay : )

2024-11-27 18:00 UTC, milescrawford commented
Okay! I'll reopen for you. No rush or pressure of course :)

2025-01-20 22:28 UTC, RobertChrist commented
@milescrawford I've been playing with this over the last 2 days of the long weekend, I think its looking pretty good.  It implements everything we've talked about above.

I've exported my josekiData if you want to see how I've been using it.

What do you think?

[josekiData.json](https://github.com/user-attachments/files/18482891/josekiData.json)

2025-01-21 01:35 UTC, milescrawford commented
Hey thanks for the work - looks good, especially at the code level.

Let me play with the auto stones for a minute. I set up two joseki that begin with a similar sequence, one including auto stones, the other not. When I get to the first auto move it seems to choose whether to treat it as auto or manual randomly? Is that right? It is odd to suddenly have a bunch of moves played for you, but perhaps I will get used to it.

The way it behaves when the auto stones are all at the beginning of the sequence, using them just as "setup" feels quite natural.

2025-01-21 01:42 UTC, milescrawford commented on site/joseki.js
> +        // Setup/Auto stones can only start a joseki.  They cannot be after a non-automatic move.
This isn't true - I was able to switch to "setup" stones after adding manual moves, creating that surprising situation where the cpu takes over during a joseki

2025-01-21 04:09 UTC, RobertChrist commented
Every time it goes to choose a move, the possible moves can be marked as either auto or normal.
If it chooses a normal, things continue as normal.
If it chooses an auto, it will automatically play it.

So if you have a few josekis that have startup stones, when that joseki is selected, it'll play the startup stones.
But if you also have a few josekis that have the same starting stones, but marked as manual, then, depending on which path through the joseki tree gets randomly selected, it might wait for you to play them first.

Depends how you set it up

2025-01-21 04:10 UTC, RobertChrist commented on site/joseki.js
> +        // Setup/Auto stones can only start a joseki.  They cannot be after a non-automatic move.
I am surprised by this?  I can't seem to recreate on Chrome or FF.  Are we sure your local code is fully pulled?  I force pushed this branch before messaging you

2025-01-21 04:59 UTC, milescrawford commented on site/joseki.js
> +        // Setup/Auto stones can only start a joseki.  They cannot be after a non-automatic move.
Oh well that is exactly why then, I didn't notice the setting.

2025-01-21 05:06 UTC, milescrawford commented
> Every time it goes to choose a move, the possible moves can be marked as either auto or normal. If it chooses a normal, things continue as normal. If it chooses an auto, it will automatically play it.

Ah nice okay. But sometimes I will play a move that triggers an auto sequence - is that intended? Makes sense for the AI to play all the setup stones to begin a problem, but if I open with a stone that matches a setup, it sometimes triggers the whole setup. See video.

https://github.com/user-attachments/assets/7737f682-fe41-49e2-b8ce-61e1ff187c60

2025-01-21 06:26 UTC, RobertChrist commented
So I think what happened here, is you have (at least) two joseki defined.  They both have the same moves, but one is all manual moves, the other uses setup stones for the first few moves.

When the game tree builds, it treats automatic and manual stones as different branches in the tree, so you shouldn't ever end up jumping back and forth between them (like is happening here).  But when you choose your first move, both branches are available, and I wasn't treating the user's click as a manual move (though of course it is).

I believe the fix would be : https://github.com/RobertChrist/joseki/commit/a24e2c59476a723805c0b79f5bd99d37266baa3f

Unfortunately, I am not going to have a chance to test this for quite some time.  Work has gotten quite intense.  This weekend was the first chance I'd had to personally code again since we spoke in November : /

2025-01-21 06:51 UTC, milescrawford commented
I merged that commit locally and it appears to work at first inspection. If you want to merge it into this PR I can test a bit more. Are we close to a merge? Or do you still feel in progress?

One other odd effect of the setup stones code is that the player (black) does not get to choose a starting move half the time anymore - perhaps because the setup stones start with black, many of the player's chances to choose an opening stone are taken by setup moves. Maybe this is desirable if all the joseki you're practicing use setup stones, but it's odd that you have so few chances to play first when some don't.

2025-01-26 18:07 UTC, milescrawford commented
Replaced by #16

2025-01-26 18:07 UTC, closed without merging